### ISSUE TITLE
Random result in search_exact test

### ISSUE THREAD

**Issue by torognes** [frederic-mahe/vsearch-tests#2]
The search_exact test with the description `--uc match orientation is correct in 5th column with H (-)` gives random results. The test fails in about 1% of the times I run it.

This test produces two lines lines of output, usually with a plus in column 5 on the first line and a minus on the second line. However, occasionally the two lines are in the opposite order. I think this is due to the use of multiple threads and to the fact that the order of the results may then be non-deterministic. This is generally the case when using multiple threads with vsearch.

I think the test should be changed to check that the minus is in the 5th column on the line with s2 in the 9th column.

**Comment by frederic-mahe** [comment]
The tests can be simplified to avoid that problem altogether. Solved in https://github.com/frederic-mahe/vsearch-tests/commit/3a042195f93c4bc56169a566550593f025e1bcca
